Tivoy/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataModels;
using Microsoft.AspNetCore.Identity;
using DataAccess.Models;
using DataAccess.Repositories;

namespace Tivoy.Controllers
{
    public class CustomerController : BaseController
    {
        public CustomerController(UserManager<User> userManager,
                               SignInManager<User> signInManager,
                               IUnitOfWork unitOfWork
                             ) : base(userManager, signInManager, unitOfWork)
        {

        }
        public async Task<IActionResult> Index()
        {
            var model = await UnitOfWork.CustomerRepository.GetAll();
            return View(model);
        }
        [HttpGet]
        public  async Task<IActionResult> Add(int?id)
        {
            var model = id.HasValue ? await UnitOfWork.CustomerRepository.GetById(id.Value) : new CustomerViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CustomerViewModel model)
        {
            if(model.Id==0)
            {
 var user = new User
            { UserName = model.Email,
              Email = model.Email,

                };
           var result=await UserManager.CreateAsync(user,"Aa.1234566");
            if(result.Succeeded)
            {
                model.UserId = user.Id;
                int newCustomerId= await UnitOfWork.CustomerRepository.Add(model);
                return RedirectToAction("Profile", new { Id =newCustomerId});
            }
            }
            else
            {
                await UnitOfWork.CustomerRepository.Update(model);
                return RedirectToAction("Profile", new { model.Id });
            }
            return View();
        }

        public async Task<IActionResult> Profile(int Id)
        {
            var model = await UnitOfWork.CustomerRepository.GetById(Id);
            return View(model);
        }

        
        public async Task<JsonResult> AddNote(NoteViewModel model)
        {
            await UnitOfWork.CustomerRepository.AddNote(model.Text, model.UserId);
            return Json(new {success=true });
        }
    }
}

Tivoy/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccess.Models;
using DataAccess.Repositories;
using DataModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;

namespace Tivoy.Controllers
{
    public class OrderController : BaseController
    {
        public OrderController(UserManager<User> userManager,
                              SignInManager<User> signInManager,
                              IUnitOfWork unitOfWork
                            ) : base(userManager, signInManager, unitOfWork)
        {

        }
        public async Task<IActionResult> Index(string searchString, string currentFilter, int? page, int? pageSize)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            int pSize = pageSize ?? 10;
            ViewBag.PageSize = pSize;

            if (searchString != null)
            {
                searchString = searchString.Trim();
            }

            page = page ?? 1;

            var orders = await UnitOfWork.OrderRepository.GetAllPagedList(page.Value, pSize, searchString);
            return Request.IsAjaxRequest()
               ? (ActionResult)PartialView("_List", orders)
               : View(orders);
        }
        [HttpGet]
        public async Task<IActionResult> Create(int? Id,int? tourId)
        {
            var users = await UnitOfWork.CustomerRepository.GetAll();
            if(Id.HasValue)
            {
               
                ViewBag.isOneUser = true;
            }
            ViewBag.Customers = new SelectList(users, "Id", "FullName",Id);

            var tours = await UnitOfWork.TourRepository.GetAll();
            ViewBag.Tours = new SelectList(tours, "Id", "Name",tourId);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderViewModel model)
        {
            await UnitOfWork.OrderRepository.Add(model);
            return RedirectToAction("Index");
        }
    }
}

Tivoy/Views/Customer/Add.cshtml
@model CustomerViewModel
@{
    ViewData["Title"] = "Add";
    bool isEdit = Model.Id > 0;
    string buttonText = isEdit ? "Update" : "Add";
}
<div class="card">
    <div class="card-block">
        <form asp-controller="Customer" asp-action="Add" method="post">
            <div class="form-group">
                <label asp-for="FirstName">First Name</label>
                <input type="text" asp-for="FirstName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="LastName">Last Name</label>
                <input type="text" asp-for="LastName" class="form-control" />
            </div>
            <div class="form-group">
                <label for="Gender">Gender</label>
                <select asp-for="Gender" class="form-control">
                    <option>Please select</option>
                    <option value="1">Male</option>
                    <option value="2">Female</option>
                    <option value="3">Other</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate">Birth Date</label>
                <input type="text" asp-for="BirthDate" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="VisaExpiredate">Visa Expire Date</label>
                <input type="text" asp-for="VisaExpiredate" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PassportIdNumber">ID Number</label>
                <input type="text" asp-for="PassportIdNumber" class="form-control"/>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber">Phone Number</label>
                <input type="text" asp-for="PhoneNumber" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Email">E-mail</label>
                <input type="text" asp-for="Email" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="CityId">City</label>
                <select asp-for="CityId" class="form-control">
                    <option>Please select</option>
                    <option value="1">London</option>
                    <option value="2">Madrid</option>
                    <option value="3">Rome</option>
                </select>
            </div>
            <button class="btn btn-success pull-right" type="button">+</button>
            <br /><button type="submit" class="btn btn-success">@buttonText</button>
        </form>
    </div>
    
</div>

Tivoy/Views/Customer/Index.cshtml
@model IEnumerable<CustomerViewModel>
@{
    ViewData["Title"] = "Index";
}

<header class="content__title">
    <h1>Clients</h1>
    <a asp-controller="Customer" asp-action="Add" class="btn btn-success mt-3">Add new</a>
    <div class="actions">
        <a href="" class="actions__item zmdi zmdi-trending-up"></a>
        <a href="" class="actions__item zmdi zmdi-check-all"></a>
        <div class="dropdown actions__item">
            <i data-toggle="dropdown" class="zmdi zmdi-more-vert"></i>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="" class="dropdown-item">Refresh</a>
                <a href="" class="dropdown-item">Manage Widgets</a>
                <a href="" class="dropdown-item">Settings</a>
            </div>
        </div>
    </div>
</header>

<div class="card">
    <div class="card-header">
     
    </div>
    <div class="card-block">
        <div class="table-responsive">
            <table  class="table">
                <thead>
                    <tr>
                        <th>Full Name</th>
                        <th>E-mail</th>
                        <th>Phone</th>
                        <th>City</th>
                        <th>Orders</th>
                        <th></th>
                    </tr>
                </thead>
                
                <tbody>
                   
                  @foreach(var item in Model)
                  {
                    <tr>
                        <td>@item.FullName</td>
                        <td>@item.Email</td>
                        <td>@item.PhoneNumber</td>
                        <td>@item.CityName</td>
                        <td>@item.OrderCount</td>
                        <td>
                            <a asp-controller="Customer" asp-action="Add" asp-route-id="@item.Id" class="btn btn-success">Edit</a>
                            <a asp-controller="Customer" asp-action="Profile" asp-route-id="@item.Id" class="btn btn-default">View Profile</a>
                            <a href="#" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                  }
                    
                </tbody>
            </table>
        </div>
    </div>
</div>

Tivoy/Views/Customer/Profile.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@model CustomerViewModel
@{
    ViewData["Title"] = "Profile";
}
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-block">
                <h2>Basic Info</h2>
                <div class="mb-2">
                    @Model.FullName
                </div>
                <div class="mb-2">
                    Orders: @Model.Orders.Count
                </div>
                <div class="mb-2">
                    E-mail:  @Model.Email
                </div>
                <div class="mb-2">
                    Number:  @Model.PhoneNumber
                </div>
                <div class="mb-2">
                    <a asp-controller="Order" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-success">Add new order</a>
                </div>
            </div>
        </div>

    </div>
    <div class="col-md-8">

        <div class="card">
            <div class="card-block">
                <div class="tab-container">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#home" role="tab">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#profile" role="tab">Personal Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#messages" role="tab">Notes (<span id="notescount">@Model.Notes.Count</span>)</a>
                        </li>

                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active fade show" id="home" role="tabpanel">
                            @if (Model.Orders.Any())
                            {
                                @await Html.PartialAsync("~/Views/Order/_List.cshtml", Model.Orders.ToPagedList())
                            }
                        </div>
                        <div class="tab-pane fade" id="profile" role="tabpanel">
                            <div class="card-block">
                                <div class="mt-4">
                                    <span>Full Name:</span> <strong>@Model.FullName</strong>
                                </div>
                                <div class="mt-4">
                                    <span>Date of Birth:</span> <strong>@Model.DisplayBirthDate</strong>
                                </div>
                                <div class="mt-4">
                                    <span>Gender:</span> <strong>@Model.DisplayGender</strong>
                                </div>
                                <div class="mt-4">
                                    <span>City:</span> <strong>@Model.CityName</strong>
                                </div>
                                <div class="mt-4">
                                    <span>ID Number</span> <strong>@Model.PassportIdNumber</strong>
                                </div>
                                <div class="mt-3">
                                    <span>Visa Permition</span>
                                    @if (Model.ActiveVisa)
                                    {
                                        <div class="btn-group btn-group--colors">
                                            <label class="custom-control custom-checkbox" title="@Model.VisaDaysLeft">
                                                <input type="checkbox" checked disabled class="custom-control-input" />

                                                <span class="custom-control-indicator"></span>

                                            </label>
                                        </div>
                                    }
                                </div>
                                <div class="mt-3">
                                    <span>Phone Number</span> <strong>@Model.PhoneNumber</strong>
                                </div>
                                <div class="mt-3">
                                    <span>E-mail</span> <strong>@Model.Email</strong>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="messages" role="tabpanel">
                            <div class="row">
                                <div class="col-md-8">
                                    <input type="hidden" value="@Model.Id" id="customerId" />
                                    <textarea class="form-control" id="noteText">

</textarea>
                                </div>
                                <div class="col-md-4">
                                    <button class="btn btn-success" id="addNote">Add</button>
                                </div>
                            </div>
                            <div class="notes">
                                @foreach (var item in Model.Notes)
                                {
                                    <div class="note mt-3">
                                        <strong>@item.AddDate.ToShortDateString()</strong>
                                        <br />@item.Text
                                    </div>
                                }
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


@section Scripts{
    <script>
var noteUrl="@Url.Action("AddNote")";
    </script>

}