Tivoy/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccess.Models;
using DataAccess.Repositories;
using DataModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;

namespace Tivoy.Controllers
{
    public class OrderController : BaseController
    {
        public OrderController(UserManager<User> userManager,
                              SignInManager<User> signInManager,
                              IUnitOfWork unitOfWork
                            ) : base(userManager, signInManager, unitOfWork)
        {

        }
        public async Task<IActionResult> Index(string searchString, string currentFilter, int? page, int? pageSize)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            int pSize = pageSize ?? 10;
            ViewBag.PageSize = pSize;

            if (searchString != null)
            {
                searchString = searchString.Trim();
            }

            page = page ?? 1;

            var orders = await UnitOfWork.OrderRepository.GetAllPagedList(page.Value, pSize, searchString);
            return Request.IsAjaxRequest()
               ? (ActionResult)PartialView("_List", orders)
               : View(orders);
        }
        [HttpGet]
        public async Task<IActionResult> Create(int? Id,int? tourId)
        {
            var users = await UnitOfWork.CustomerRepository.GetAll();
            if(Id.HasValue)
            {
               
                ViewBag.isOneUser = true;
            }
            ViewBag.Customers = new SelectList(users, "Id", "FullName",Id);

            var tours = await UnitOfWork.TourRepository.GetAll();
            ViewBag.Tours = new SelectList(tours, "Id", "Name",tourId);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderViewModel model)
        {
            await UnitOfWork.OrderRepository.Add(model);
            return RedirectToAction("Index");
        }
    }
}

Tivoy/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using DataModels;

namespace Tivoy.Controllers
{
    public class TourController : BaseController
    {
        public TourController(UserManager<User> userManager,
                             SignInManager<User> signInManager,
                             IUnitOfWork unitOfWork
                           ) : base(userManager, signInManager, unitOfWork)
        {

        }

        public async Task<IActionResult> Index()
        {
            var tours = await UnitOfWork.TourRepository.GetAll();
            return View(tours);
        }

        [HttpGet]
        public async Task<IActionResult> Add(int? id)
        {
            var model = id.HasValue ? await UnitOfWork.TourRepository.GetById(id.Value) : new TourViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(TourViewModel model)
        {


            try
            {
                if (ModelState.IsValid)
                {
                    await UnitOfWork.TourRepository.Add(model);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);

            }
            return View("Add", model);

        }
    }
}

Tivoy/Views/Tour/Add.cshtml
@model DataModels.TourViewModel
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
    <div class="card-block">
        <form asp-controller="Tour" asp-action="Add" method="post">
            <div class="form-group">
                <label asp-for="Name"> Name</label>
                <input type="text" asp-for="Name" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="MoreInfo">More Info</label>
                <input type="text" asp-for="MoreInfo" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description">Description</label>
                <input type="text" asp-for="Description" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Rate">Rate</label>
                <input type="text" asp-for="Rate" class="form-control" />
            </div>
            
            <div class="form-group">
                <label asp-for="Price">Price</label>
                <input type="text" asp-for="Price" class="form-control" />
            </div>   
            <button type="submit" value="Add" class="btn btn-success ">Add</button>
        </form>
    </div>

</div>

Tivoy/Views/Tour/Index.cshtml
@model List<DataModels.TourViewModel>
@{
    ViewData["Title"] = "Index";
}

<header class="content__title">
    <h1>Tours and activities</h1>
    <a asp-controller="Tour" asp-action="Add" class="btn btn-success mt-3">Add new tour package</a>
    
</header>
    @*<header class="content__title">
            <h1>Images</h1>
            <small>Cards can also include images in the top and bottom.</small>
        </header>*@
<div class="row">
    <div class="col-md-12">
        @foreach (var item in Model)
        {
            <div class="card-demo col-md-6">
                <div class="card col-md-12">
                    <img class="card-img-top" src="~/material/img/headers/5.png">
                    <div class="card-header">
                        <h2 class="card-title">@item.Name</h2>
                        <small class="card-subtitle">@item.MoreInfo</small>
                    </div>
                    <div class="card-block">
                        <p>@item.Description</p>
                    </div>
                    <div class="card-header">
                        <button class="btn btn-link pull-right">See more</button>
                    </div>
                    <div class="card-block">
                        @for (var i = 1; i <= item.Rate; i++)
                        {
                            <i class="zmdi zmdi-star zmdi-hc-3x"> </i>
                        }
                        @for (var i = (item.Rate + 1); i <= 5; i++)
                        {
                            <i class="zmdi zmdi-star-border zmdi-hc-3x"></i>
                        }
                    </div>
                    <div class="card-block">
                        <h4 class="pull-right">Price:@item.Price $</h4>
                    </div>
                    <div class="card-block">
                        <a class="btn btn-success" asp-controller="Order" asp-action="Create" asp-route-tourId="@item.Id">New Order</a>
                        <button class="btn btn-primary pull-right"><i class="zmdi zmdi-facebook-box zmdi-hc-lg"> </i> Boost on Facebook</button>
                    </div>
                </div>
            </div>
        }
        </div>
    </div>